region_map <- tribble(
    ~country, ~region,
    "United States", "North America",
    "Canada", "North America",
    "Mexico", "North America",
    "United Kingdom", "Europe",
    "France", "Europe",
    "Germany", "Europe",
    "Italy", "Europe",
    "Spain", "Europe",
    "Belgium", "Europe",
    "Netherlands", "Europe",
    "Sweden", "Europe",
    "Denmark", "Europe",
    "Norway", "Europe",
    "Ireland", "Europe",
    "Portugal", "Europe",
    "Switzerland", "Europe",
    "Poland", "Europe",
    "Czech Republic", "Europe",
    "Russia", "Europe",
    "Turkey", "Asia",
    "India", "Asia",
    "China", "Asia",
    "Japan", "Asia",
    "South Korea", "Asia",
    "Hong Kong", "Asia",
    "Taiwan", "Asia",
    "Indonesia", "Asia",
    "Philippines", "Asia",
    "Malaysia", "Asia",
    "Singapore", "Asia",
    "Pakistan", "Asia",
    "Thailand", "Asia",
    "Vietnam", "Asia",
    "United Arab Emirates", "Middle East",
    "Saudi Arabia", "Middle East",
    "Egypt", "Africa",
    "South Africa", "Africa",
    "Nigeria", "Africa",
    "Kenya", "Africa",
    "Argentina", "Latin America",
    "Brazil", "Latin America",
    "Chile", "Latin America",
    "Colombia", "Latin America",
    "Uruguay", "Latin America",
    "Peru", "Latin America",
    "Venezuela", "Latin America",
    "Australia", "Oceania",
    "New Zealand", "Oceania"
)